var __v="\u003cpre class='k-pre'\u003e除了在 訂閱者的 error 回調中 處理錯誤外\n還可以使用 catchError 來捕獲\ncatchError 返回一個 可觀察對象 以供 訂閱者 獲取值 否則 throw 來通知錯誤\u003c/pre\u003e\n\n\u003cpre class='prettyprint linenums'\u003eimport { Component, OnInit } from '@angular/core';\nimport { of } from \"rxjs/observable/of\";\nimport { map, filter, catchError } from 'rxjs/operators';\n\n@Component({\n  selector: 'app-view1',\n  templateUrl: './view1.component.html',\n  styleUrls: ['./view1.component.css']\n})\nexport class View1Component implements OnInit {\n\n  constructor() { }\n\n  ngOnInit() {\n    // 創建 Observable\n    let observable = of(0, 1, 2, 3).pipe(\n      map((v: number) =\u0026gt; {\n        if (v == 3) {\n          throw 3\n        }\n        return v;\n      }),\n      catchError((e) =\u0026gt; {\n        return of(0, 1, 2);\n      }),\n    );\n\n    // 訂閱\n    observable.subscribe({\n      next(v) { console.log(\"val = \", v); },\n      error(e) { console.error('Error: ' + e); },\n      complete() { console.log('Completed'); }\n    });\n  }\n}\n\u003c/pre\u003e"